apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}-worker
    chart: {{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "fullname" . }}-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-worker
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-worker
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      automountServiceAccountToken: false
      containers:
        - name: {{ template "fullname" . }}-worker
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "-m", "app.worker"]
          env:
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: docuquery
                  key: gemini-api-key
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-root-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-root-password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
            - name: REDIS_HOST
              value: {{ .Values.redis.host }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | quote }}
            - name: CHROMA_HOST
              value: {{ .Values.chroma.host }}
            - name: CHROMA_PORT
              value: {{ .Values.chroma.port | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
