"""Migrate documents from a self-hosted ChromaDB into Chroma Cloud.

Reads every record from a legacy (self-hosted) collection and re-ingests it into
a sharded Chroma Cloud collection using the project's dense + sparse Schema, so
the records are embedded with Chroma Cloud Qwen / Splade.

Example:
    python scripts/migrate_chroma.py \
        --legacy-host localhost --legacy-port 8000 \
        --source-collection documents --tenant default

Environment variables (for the Cloud client):
    CHROMA_HOST, CHROMA_API_KEY, CHROMA_TENANT, CHROMA_DATABASE
"""

import argparse
import os
from typing import Any

import chromadb
from loguru import logger

from app.db.chroma import build_schema, collection_name, SPARSE_INDEX_KEY

DOCUMENT_KINDS = ("documents", "semantic_cache")
BATCH_SIZE = 100


def _legacy_client(host: str, port: int):
    client = chromadb.HttpClient(host=host, port=port)
    logger.info(f"Connected to legacy ChromaDB at {host}:{port}")
    return client


def _legacy_records(legacy_collection) -> list[dict[str, Any]]:
    """Fetch all records from the legacy collection in column-major form."""
    limit = legacy_collection.count() or 0
    if limit == 0:
        logger.warning("Legacy collection is empty; nothing to migrate.")
        return []

    result = legacy_collection.get(limit=limit, include=["documents", "metadatas"])
    records = []
    ids = result.get("ids") or []
    documents = result.get("documents") or []
    metadatas = result.get("metadatas") or [None] * len(ids)
    for record_id, document, metadata in zip(ids, documents, metadatas):
        records.append({"id": record_id, "document": document, "metadata": metadata or {}})
    logger.info(f"Read {len(records)} records from legacy collection.")
    return records


def _normalize_metadata(record: dict[str, Any], tenant: str) -> dict[str, Any]:
    meta = dict(record["metadata"])
    # Ensure document_id + chunk_index are present for GroupBy dedup.
    meta.setdefault("document_id", record["id"].rsplit("-", 1)[0])
    meta.setdefault("chunk_index", 0)
    meta.setdefault("source", meta.get("source", record["id"]))
    meta.setdefault("user_id", tenant)
    meta.pop(SPARSE_INDEX_KEY, None)  # sparse vectors are regenerated by the schema
    return meta


def migrate(
    legacy_client,
    cloud_client,
    tenant: str,
    kind: str = "documents",
    source_collection: str | None = None,
) -> int:
    legacy_collection = legacy_client.get_collection(
        source_collection or collection_name(kind, None)
    )
    records = _legacy_records(legacy_collection)
    if not records:
        return 0

    name = collection_name(kind, tenant)
    schema = build_schema()
    target = cloud_client.get_or_create_collection(name=name, schema=schema)
    logger.info(f"Target collection: {name} (schema: {'attached' if schema else 'none'})")

    migrated = 0
    for start in range(0, len(records), BATCH_SIZE):
        batch = records[start:start + BATCH_SIZE]
        target.upsert(
            ids=[r["id"] for r in batch],
            documents=[r["document"] for r in batch if r["document"] is not None],
            metadatas=[_normalize_metadata(r, tenant) for r in batch],
        )
        migrated += len(batch)
        logger.info(f"Migrated {migrated}/{len(records)} records")

    return migrated


def main():
    parser = argparse.ArgumentParser(description="Migrate ChromaDB records to Chroma Cloud.")
    parser.add_argument("--legacy-host", default="localhost", help="Legacy ChromaDB host.")
    parser.add_argument("--legacy-port", type=int, default=8000, help="Legacy ChromaDB port.")
    parser.add_argument(
        "--source-collection",
        default=None,
        help="Legacy collection name. Defaults to the app's collection name.",
    )
    parser.add_argument("--tenant", default="default", help="Tenant/org to shard into.")
    parser.add_argument(
        "--kind",
        choices=DOCUMENT_KINDS,
        default="documents",
        help="Which kind of data to migrate.",
    )
    args = parser.parse_args()

    legacy_client = _legacy_client(args.legacy_host, args.legacy_port)

    if not os.getenv("CHROMA_API_KEY"):
        raise SystemExit("CHROMA_API_KEY is not set. Configure it before migrating.")

    cloud_client = chromadb.CloudClient(
        tenant=os.getenv("CHROMA_TENANT"),
        database=os.getenv("CHROMA_DATABASE", "docuquery"),
        api_key=os.getenv("CHROMA_API_KEY"),
        cloud_host=os.getenv("CHROMA_HOST", "api.trychroma.com"),
        cloud_port=int(os.getenv("CHROMA_PORT", "443")),
    )

    migrated = migrate(
        legacy_client,
        cloud_client,
        args.tenant,
        kind=args.kind,
        source_collection=args.source_collection,
    )
    logger.info(f"Migration complete. {migrated} records migrated for tenant '{args.tenant}'.")


if __name__ == "__main__":
    main()